
local AddonFile, RBP = ... -- namespace

local LSM = LibStub("LibSharedMedia-3.0")
local ASSETS = "Interface\\AddOns\\" .. AddonFile .. "\\Assets\\"
------------------------------------------ Status Bar Textures ------------------------------------------
LSM:Register("statusbar", "Blizzard Nameplates", "Interface\\TargetingFrame\\UI-TargetingFrame-BarFill")
LSM:Register("statusbar", "AceBarFrames", ASSETS .. "StatusBars\\AceBarFrames")
LSM:Register("statusbar", "Aluminium", ASSETS .. "StatusBars\\Aluminium")
LSM:Register("statusbar", "Armory", ASSETS .. "StatusBars\\Armory")
LSM:Register("statusbar", "BantoBar", ASSETS .. "StatusBars\\BantoBar")
LSM:Register("statusbar", "BantoBarReverse", ASSETS .. "StatusBars\\BantoBarReverse")
LSM:Register("statusbar", "Bars", ASSETS .. "StatusBars\\Bars")
LSM:Register("statusbar", "blend", ASSETS .. "StatusBars\\blend")
LSM:Register("statusbar", "Blinkii", ASSETS .. "StatusBars\\Blinkii")
LSM:Register("statusbar", "Bumps", ASSETS .. "StatusBars\\Bumps")
LSM:Register("statusbar", "Button", ASSETS .. "StatusBars\\Button")
LSM:Register("statusbar", "Cilo", ASSETS .. "StatusBars\\Cilo")
LSM:Register("statusbar", "Charcoal", ASSETS .. "StatusBars\\Charcoal")
LSM:Register("statusbar", "Clean", ASSETS .. "StatusBars\\Clean")
LSM:Register("statusbar", "Cloud", ASSETS .. "StatusBars\\Cloud")
LSM:Register("statusbar", "Comet", ASSETS .. "StatusBars\\Comet")
LSM:Register("statusbar", "Dabs", ASSETS .. "StatusBars\\Dabs")
LSM:Register("statusbar", "DarkBottom", ASSETS .. "StatusBars\\DarkBottom")
LSM:Register("statusbar", "Diagonal", ASSETS .. "StatusBars\\Diagonal")
LSM:Register("statusbar", "Falumn", ASSETS .. "StatusBars\\Falumn")
LSM:Register("statusbar", "Ferous 1", ASSETS .. "StatusBars\\Ferous1")
LSM:Register("statusbar", "Ferous 2", ASSETS .. "StatusBars\\Ferous2")
LSM:Register("statusbar", "Ferous 3", ASSETS .. "StatusBars\\Ferous3")
LSM:Register("statusbar", "Ferous 4", ASSETS .. "StatusBars\\Ferous4")
LSM:Register("statusbar", "Ferous 5", ASSETS .. "StatusBars\\Ferous5")
LSM:Register("statusbar", "Ferous 6", ASSETS .. "StatusBars\\Ferous6")
LSM:Register("statusbar", "Ferous 7", ASSETS .. "StatusBars\\Ferous7")
LSM:Register("statusbar", "Ferous 8", ASSETS .. "StatusBars\\Ferous8")
LSM:Register("statusbar", "Ferous 9", ASSETS .. "StatusBars\\Ferous9")
LSM:Register("statusbar", "Ferous 10", ASSETS .. "StatusBars\\Ferous10")
LSM:Register("statusbar", "Ferous 11", ASSETS .. "StatusBars\\Ferous11")
LSM:Register("statusbar", "Ferous 12", ASSETS .. "StatusBars\\Ferous12")
LSM:Register("statusbar", "Ferous 13", ASSETS .. "StatusBars\\Ferous13")
LSM:Register("statusbar", "Ferous 14", ASSETS .. "StatusBars\\Ferous14")
LSM:Register("statusbar", "Ferous 15", ASSETS .. "StatusBars\\Ferous15")
LSM:Register("statusbar", "Ferous 16", ASSETS .. "StatusBars\\Ferous16")
LSM:Register("statusbar", "Ferous 17", ASSETS .. "StatusBars\\Ferous17")
LSM:Register("statusbar", "Ferous 18", ASSETS .. "StatusBars\\Ferous18")
LSM:Register("statusbar", "Ferous 19", ASSETS .. "StatusBars\\Ferous19")
LSM:Register("statusbar", "Ferous 20", ASSETS .. "StatusBars\\Ferous20")
LSM:Register("statusbar", "Ferous 21", ASSETS .. "StatusBars\\Ferous21")
LSM:Register("statusbar", "Ferous 22", ASSETS .. "StatusBars\\Ferous22")
LSM:Register("statusbar", "Ferous 23", ASSETS .. "StatusBars\\Ferous23")
LSM:Register("statusbar", "Ferous 24", ASSETS .. "StatusBars\\Ferous24")
LSM:Register("statusbar", "Ferous 25", ASSETS .. "StatusBars\\Ferous25")
LSM:Register("statusbar", "Ferous 26", ASSETS .. "StatusBars\\Ferous26")
LSM:Register("statusbar", "Ferous 27", ASSETS .. "StatusBars\\Ferous27")
LSM:Register("statusbar", "Ferous 28", ASSETS .. "StatusBars\\Ferous28")
LSM:Register("statusbar", "Ferous 29", ASSETS .. "StatusBars\\Ferous29")
LSM:Register("statusbar", "Ferous 30", ASSETS .. "StatusBars\\Ferous30")
LSM:Register("statusbar", "Ferous 31", ASSETS .. "StatusBars\\Ferous31")
LSM:Register("statusbar", "Ferous 32", ASSETS .. "StatusBars\\Ferous32")
LSM:Register("statusbar", "Ferous 33", ASSETS .. "StatusBars\\Ferous33")
LSM:Register("statusbar", "Ferous 34", ASSETS .. "StatusBars\\Ferous34")
LSM:Register("statusbar", "Ferous 35", ASSETS .. "StatusBars\\Ferous35")
LSM:Register("statusbar", "Fifths", ASSETS .. "StatusBars\\Fifths")
LSM:Register("statusbar", "Flat", ASSETS .. "StatusBars\\Flat")
LSM:Register("statusbar", "Frost", ASSETS .. "StatusBars\\Frost")
LSM:Register("statusbar", "Fourths", ASSETS .. "StatusBars\\Fourths")
LSM:Register("statusbar", "Glamour", ASSETS .. "StatusBars\\Glamour")
LSM:Register("statusbar", "Glamour2", ASSETS .. "StatusBars\\Glamour2")
LSM:Register("statusbar", "Glamour3", ASSETS .. "StatusBars\\Glamour3")
LSM:Register("statusbar", "Glamour4", ASSETS .. "StatusBars\\Glamour4")
LSM:Register("statusbar", "Glamour5", ASSETS .. "StatusBars\\Glamour5")
LSM:Register("statusbar", "Glamour6", ASSETS .. "StatusBars\\Glamour6")
LSM:Register("statusbar", "Glamour7", ASSETS .. "StatusBars\\Glamour7")
LSM:Register("statusbar", "Glass", ASSETS .. "StatusBars\\Glass")
LSM:Register("statusbar", "Glaze", ASSETS .. "StatusBars\\Glaze")
LSM:Register("statusbar", "Gloss", ASSETS .. "StatusBars\\Gloss")
LSM:Register("statusbar", "Gradient", ASSETS .. "StatusBars\\Gradient")
LSM:Register("statusbar", "Graphite", ASSETS .. "StatusBars\\Graphite")
LSM:Register("statusbar", "Grid", ASSETS .. "StatusBars\\Grid")
LSM:Register("statusbar", "Hatched", ASSETS .. "StatusBars\\Hatched")
LSM:Register("statusbar", "Healbot", ASSETS .. "StatusBars\\Healbot")
LSM:Register("statusbar", "KhalBar", ASSETS .. "StatusBars\\KhalBar")
LSM:Register("statusbar", "LiteStep", ASSETS .. "StatusBars\\LiteStep")
LSM:Register("statusbar", "LiteStepLite", ASSETS .. "StatusBars\\LiteStepLite")
LSM:Register("statusbar", "Lyfe", ASSETS .. "StatusBars\\Lyfe")
LSM:Register("statusbar", "Melli", ASSETS .. "StatusBars\\Melli")
LSM:Register("statusbar", "Melli Dark", ASSETS .. "StatusBars\\MelliDark")
LSM:Register("statusbar", "Melli Dark Rough", ASSETS .. "StatusBars\\MelliDarkRough")
LSM:Register("statusbar", "Minimalist", ASSETS .. "StatusBars\\Minimalist")
LSM:Register("statusbar", "Norm", ASSETS .. "StatusBars\\Norm")
LSM:Register("statusbar", "Otravi", ASSETS .. "StatusBars\\Otravi")
LSM:Register("statusbar", "Perl", ASSETS .. "StatusBars\\Perl")
LSM:Register("statusbar", "Perl v2", ASSETS .. "StatusBars\\Perl2")
LSM:Register("statusbar", "Raeli 1", ASSETS .. "StatusBars\\Raeli1.tga")
LSM:Register("statusbar", "Raeli 2", ASSETS .. "StatusBars\\Raeli2.tga")
LSM:Register("statusbar", "Raeli 3", ASSETS .. "StatusBars\\Raeli3.tga")
LSM:Register("statusbar", "Raeli 4", ASSETS .. "StatusBars\\Raeli4.tga")
LSM:Register("statusbar", "Raeli 5", ASSETS .. "StatusBars\\Raeli5.tga")
LSM:Register("statusbar", "Raeli 6", ASSETS .. "StatusBars\\Raeli6.tga")
LSM:Register("statusbar", "Rain", ASSETS .. "StatusBars\\Rain")
LSM:Register("statusbar", "Rocks", ASSETS .. "StatusBars\\Rocks")
LSM:Register("statusbar", "Ruben", ASSETS .. "StatusBars\\Ruben")
LSM:Register("statusbar", "Runes", ASSETS .. "StatusBars\\Runes")
LSM:Register("statusbar", "Skewed", ASSETS .. "StatusBars\\Skewed")
LSM:Register("statusbar", "Smooth", ASSETS .. "StatusBars\\Smooth")
LSM:Register("statusbar", "Smooth v2", ASSETS .. "StatusBars\\Smoothv2")
LSM:Register("statusbar", "Smudge", ASSETS .. "StatusBars\\Smudge")
LSM:Register("statusbar", "Steel", ASSETS .. "StatusBars\\Steel")
LSM:Register("statusbar", "Striped", ASSETS .. "StatusBars\\Striped")
LSM:Register("statusbar", "Stripes", ASSETS .. "StatusBars\\Stripes")
LSM:Register("statusbar", "Thick Stripes", ASSETS .. "StatusBars\\Thick Stripes")
LSM:Register("statusbar", "Thin Stripes", ASSETS .. "StatusBars\\Thin Stripes")
LSM:Register("statusbar", "ToxiUI Clean", ASSETS .. "StatusBars\\ToxiUI-clean")
LSM:Register("statusbar", "ToxiUI Dark", ASSETS .. "StatusBars\\ToxiUI-dark")
LSM:Register("statusbar", "Water", ASSETS .. "StatusBars\\Water")
LSM:Register("statusbar", "Wglass", ASSETS .. "StatusBars\\Wglass")
LSM:Register("statusbar", "Wisps", ASSETS .. "StatusBars\\Wisps")
LSM:Register("statusbar", "Xeon", ASSETS .. "StatusBars\\Xeon")

---------------------------------------------- Text Fonts ----------------------------------------------
LSM:Register("font", "Accidental Presidency", ASSETS .. "Fonts\\AccidentalPresidency.ttf")
LSM:Register("font", "Action Man", ASSETS .. "Fonts\\ActionMan.ttf")
LSM:Register("font", "Adventure", ASSETS .. "Fonts\\Adventure.ttf")
LSM:Register("font", "Alba Super", ASSETS .. "Fonts\\AlbaSuper.ttf")
LSM:Register("font", "All Hooked Up", ASSETS .. "Fonts\\AllHookedUp.ttf")
LSM:Register("font", "Ancient Geek", ASSETS .. "Fonts\\AncientGeek.ttf")
LSM:Register("font", "Arm Wrestler", ASSETS .. "Fonts\\ArmWrestler.ttf")
LSM:Register("font", "Augustus", ASSETS .. "Fonts\\Augustus.ttf")
LSM:Register("font", "Aurora", ASSETS .. "Fonts\\Aurora.ttf")
LSM:Register("font", "Aurora Extended", ASSETS .. "Fonts\\AuroraExtended.ttf")
LSM:Register("font", "AvantGarde LT Medium", ASSETS .. "Fonts\\AvantGardeLTMedium.ttf")
LSM:Register("font", "AvantGarde LT Bold", ASSETS .. "Fonts\\AvantGardeLTBold.ttf")
LSM:Register("font", "Avanti", ASSETS .. "Fonts\\Avanti.ttf", LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register("font", "AvQest", ASSETS .. "Fonts\\AvQest.ttf")
LSM:Register("font", "Baar Sophia", ASSETS .. "Fonts\\BaarSophia.ttf")
LSM:Register("font", "Bavaria", ASSETS .. "Fonts\\Bavaria.ttf")
LSM:Register("font", "Bavaria Extended", ASSETS .. "Fonts\\BavariaExtended.ttf")
LSM:Register("font", "Bazooka", ASSETS .. "Fonts\\Bazooka.ttf")
LSM:Register("font", "BigNoodleToo", ASSETS .. "Fonts\\BigNoodleToo.ttf", LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register("font", "BigNoodleTitling", ASSETS .. "Fonts\\BigNoodleTitling.ttf")
LSM:Register("font", "Black Chancery", ASSETS .. "Fonts\\BlackChancery.ttf")
LSM:Register("font", "Blazed", ASSETS .. "Fonts\\Blazed.ttf")
LSM:Register("font", "Blender Pro", ASSETS .. "Fonts\\BlenderPro.ttf", LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register("font", "Blender Pro Bold", ASSETS .. "Fonts\\BlenderProBold.ttf", LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register("font", "Blender Pro Heavy", ASSETS .. "Fonts\\BlenderProHeavy.ttf", LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register("font", "Boris Black Bloxx Dirty", ASSETS .. "Fonts\\BorisBlackBloxxDirty.ttf")
LSM:Register("font", "Boris Black Bloxx", ASSETS .. "Fonts\\BorisBlackBloxx.ttf")
LSM:Register("font", "Caesar", ASSETS .. "Fonts\\Caesar.ttf")
LSM:Register("font", "Capitalis Type Oasis", ASSETS .. "Fonts\\CapitalisTypeOasis.ttf")
LSM:Register("font", "Celestia Medium Redux", ASSETS .. "Fonts\\CelestiaMediumRedux.ttf", LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register("font", "Collegiate", ASSETS .. "Fonts\\Collegiate.ttf")
LSM:Register("font", "Cooline", ASSETS .. "Fonts\\Cooline.ttf")
LSM:Register("font", "Continuum Medium", ASSETS .. "Fonts\\ContinuumMedium.ttf")
LSM:Register("font", "DejaVu Sans", ASSETS .. "Fonts\\DejaVuLGCSans.ttf", LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register("font", "DejaVu Serif", ASSETS .. "Fonts\\DejaVuLGCSerif.ttf", LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register("font", "DieDieDie", ASSETS .. "Fonts\\DieDieDie.ttf", LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register("font", "Diogenes", ASSETS .. "Fonts\\Diogenes.ttf")
LSM:Register("font", "Disko", ASSETS .. "Fonts\\Disko.ttf")
LSM:Register("font", "Disney Heroic", ASSETS .. "Fonts\\DisneyHeroic.ttf")
LSM:Register("font", "Doris PP", ASSETS .. "Fonts\\DorisPP.ttf")
LSM:Register("font", "Emblem", ASSETS .. "Fonts\\Emblem.ttf")
LSM:Register("font", "Enigmatic", ASSETS .. "Fonts\\Enigmatic.ttf")
LSM:Register("font", "Eurasia", ASSETS .. "Fonts\\Eurasia.ttf")
LSM:Register("font", "Exocet Blizzard Light", ASSETS .. "Fonts\\ExocetBlizzardLight.ttf", LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register("font", "Exocet Blizzard Medium", ASSETS .. "Fonts\\ExocetBlizzardMedium.ttf", LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register("font", "Expressway", ASSETS .. "Fonts\\Expressway.ttf", LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register("font", "Fira Mono Medium", ASSETS .. "Fonts\\FiraMonoMedium.ttf", LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register("font", "Fitzgerald", ASSETS .. "Fonts\\Fitzgerald.ttf")
LSM:Register("font", "FORCED SQUARE", ASSETS .. "Fonts\\FORCEDSQUARE.ttf")
LSM:Register("font", "Frakturika Spamless", ASSETS .. "Fonts\\FrakturikaSpamless.ttf")
LSM:Register("font", "FrancoisOne", ASSETS .. "Fonts\\FrancoisOne.ttf")
LSM:Register("font", "Frucade", ASSETS .. "Fonts\\Frucade.ttf")
LSM:Register("font", "Frucade Small", ASSETS .. "Fonts\\FrucadeSmall.ttf")
LSM:Register("font", "Frucade Medium", ASSETS .. "Fonts\\FrucadeMedium.ttf")
LSM:Register("font", "Frucade Extended", ASSETS .. "Fonts\\FrucadeExtended.ttf")
LSM:Register("font", "Futura PT Bold", ASSETS .. "Fonts\\FuturaPTBold.ttf", LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register("font", "Futura PT Book", ASSETS .. "Fonts\\FuturaPTBook.ttf", LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register("font", "Futura PT Medium", ASSETS .. "Fonts\\FuturaPTMedium.ttf", LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register("font", "Gentium Plus", ASSETS .. "Fonts\\GentiumPlus.ttf", LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register("font", "Germanica Embossed", ASSETS .. "Fonts\\GermanicaEmbossed.ttf")
LSM:Register("font", "Germanica Fluted", ASSETS .. "Fonts\\GermanicaFluted.ttf")
LSM:Register("font", "Germanica Shadowed", ASSETS .. "Fonts\\GermanicaShadowed.ttf")
LSM:Register("font", "Ginko", ASSETS .. "Fonts\\Ginko.ttf")
LSM:Register("font", "Gotham Ultra", ASSETS .. "Fonts\\GothamUltra.ttf")
LSM:Register("font", "Gros", ASSETS .. "Fonts\\Gros.ttf")
LSM:Register("font", "Gros Extended", ASSETS .. "Fonts\\GrosExtended.ttf")
LSM:Register("font", "Hack", ASSETS .. "Fonts\\Hack.ttf", LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register("font", "Harry Potter", ASSETS .. "Fonts\\HarryP.ttf")
LSM:Register("font", "Homespun", ASSETS .. "Fonts\\Homespun.ttf", LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register("font", "Impact", ASSETS .. "Fonts\\Impact.ttf", LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register("font", "King Arthur Legend", ASSETS .. "Fonts\\KingArthurLegend.ttf")
LSM:Register("font", "Liberation Sans", ASSETS .. "Fonts\\LiberationSans.ttf", LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register("font", "Liberation Serif", ASSETS .. "Fonts\\LiberationSerif.ttf", LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register("font", "Marke Eigenbau", ASSETS .. "Fonts\\MarkeEigenbau.ttf")
LSM:Register("font", "Memoria Extended", ASSETS .. "Fonts\\MemoriaExtended.ttf")
LSM:Register("font", "Memoria", ASSETS .. "Fonts\\Memoria.ttf")
LSM:Register("font", "Micro", ASSETS .. "Fonts\\Micro.ttf")
LSM:Register("font", "Myriad Condensed Web", ASSETS .. "Fonts\\MyriadCondensedWeb.ttf")
LSM:Register("font", "Munica Extended", ASSETS .. "Fonts\\MunicaExtended.ttf")
LSM:Register("font", "Munica", ASSETS .. "Fonts\\Munica.ttf")
LSM:Register("font", "Mystic Orbs", ASSETS .. "Fonts\\MysticOrbs.ttf")
LSM:Register("font", "Nueva Std Cond", ASSETS .. "Fonts\\NuevaStdCond.ttf")
LSM:Register("font", "Olde English", ASSETS .. "Fonts\\OldeEnglish.ttf")
LSM:Register("font", "Oswald", ASSETS .. "Fonts\\Oswald.ttf")
LSM:Register("font", "Pokemon Solid", ASSETS .. "Fonts\\PokemonSolid.ttf")
LSM:Register("font", "Porky", ASSETS .. "Fonts\\Porky.ttf")
LSM:Register("font", "Prototype", ASSETS .. "Fonts\\Prototype.ttf")
LSM:Register("font", "PT Sans Narrow", ASSETS .. "Fonts\\PTSansNarrow.ttf", LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register("font", "Quicksand", ASSETS .. "Fonts\\Quicksand.ttf")
LSM:Register("font", "RM Midserif", ASSETS .. "Fonts\\RMMidserif.ttf")
LSM:Register("font", "Rock Show Whiplash", ASSETS .. "Fonts\\RockShowWhiplash.ttf")
LSM:Register("font", "Roman SD", ASSETS .. "Fonts\\RomanSD.ttf")
LSM:Register("font", "Romanum Est", ASSETS .. "Fonts\\RomanumEst.ttf")
LSM:Register("font", "Semplice Extended", ASSETS .. "Fonts\\SempliceExtended.ttf")
LSM:Register("font", "Semplice", ASSETS .. "Fonts\\Semplice.ttf")
LSM:Register("font", "SF Atarian System", ASSETS .. "Fonts\\SFAtarianSystem.ttf")
LSM:Register("font", "SF Covington", ASSETS .. "Fonts\\SFCovington.ttf")
LSM:Register("font", "SF Diego Sans", ASSETS .. "Fonts\\SFDiegoSans.ttf")
LSM:Register("font", "SF Movie Poster", ASSETS .. "Fonts\\SFMoviePoster.ttf")
LSM:Register("font", "SF Wonder Comic", ASSETS .. "Fonts\\SFWonderComic.ttf")
LSM:Register("font", "Solange", ASSETS .. "Fonts\\Solange.ttf")
LSM:Register("font", "Star Cine", ASSETS .. "Fonts\\StarCine.ttf")
LSM:Register("font", "Steelfish Rg", ASSETS .. "Fonts\\SteelfishRg.ttf", LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register("font", "SWF!T", ASSETS .. "Fonts\\SWF!T.ttf")
LSM:Register("font", "Talismanica", ASSETS .. "Fonts\\Talismanica.ttf")
LSM:Register("font", "Taurus", ASSETS .. "Fonts\\Taurus.ttf", LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register("font", "Tellural Alt", ASSETS .. "Fonts\\TelluralAlt.ttf", LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register("font", "TGL", ASSETS .. "Fonts\\TGL.ttf", LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register("font", "Transformers", ASSETS .. "Fonts\\Transformers.ttf")
LSM:Register("font", "Trashco", ASSETS .. "Fonts\\Trashco.ttf")
LSM:Register("font", "TrashHand", ASSETS .. "Fonts\\TrashHand.ttf")
LSM:Register("font", "Triatlhon In", ASSETS .. "Fonts\\TriatlhonIn.ttf")
LSM:Register("font", "Tw Cen MT", ASSETS .. "Fonts\\TwCenMT.ttf")
LSM:Register("font", "Ubuntu Condensed", ASSETS .. "Fonts\\UbuntuCondensed.ttf", LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register("font", "Ubuntu Light", ASSETS .. "Fonts\\UbuntuLight.ttf", LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register("font", "Ultima Campagnoli", ASSETS .. "Fonts\\UltimaCampagnoli.ttf")
LSM:Register("font", "Waltograph UI", ASSETS .. "Fonts\\WaltographUI.ttf")
LSM:Register("font", "WenQuanYi Zen Hei", ASSETS .. "Fonts\\WenQuanYiZenHei.ttf", LSM.LOCALE_BIT_koKR + LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_zhCN + LSM.LOCALE_BIT_zhTW + LSM.LOCALE_BIT_western)
LSM:Register("font", "X360", ASSETS .. "Fonts\\X360.ttf", LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register("font", "Yanone Kaffeesatz Regular", ASSETS .. "Fonts\\YanoneKaffeesatzRegular.ttf")
LSM:Register("font", "Yellowjacket", ASSETS .. "Fonts\\Yellowjacket.ttf")

RBP.LSM = LSM -- namespace reference